USE mydb;
CREATE TABLE IF NOT EXISTS userCreds (
	  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	  username VARCHAR(255) NOT NULL,
	  password VARCHAR(255) NOT NULL,
	  email VARCHAR(255) NOT NULL,
	  creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	);
CREATE TABLE IF NOT EXISTS posts (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  authorID INT NOT NULL,
  FOREIGN KEY (authorID) REFERENCES usercreds(id),
  creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)